"""added country relation to city and district

Revision ID: 0d0e2d7226b4
Revises: 953aec3915e4
Create Date: 2026-04-11 09:12:25.146009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0e2d7226b4'
down_revision: Union[str, Sequence[str], None] = '953aec3915e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'city', 'country', ['country_id'], ['id'])
    op.add_column('district', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'district', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'district', type_='foreignkey')
    op.drop_column('district', 'country_id')
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'country_id')
    # ### end Alembic commands ###
