"""empty message

Revision ID: b8e720930139
Revises: 0d0e2d7226b4
Create Date: 2026-05-04 11:20:54.992290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e720930139'
down_revision: Union[str, Sequence[str], None] = '0d0e2d7226b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('city', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('shops', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shops', 'city', ['city_id'], ['id'])
    op.drop_column('shops', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'city_id')
    op.drop_column('city', 'longitude')
    op.drop_column('city', 'latitude')
    # ### end Alembic commands ###
